org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Unity Build Properties
# unity.androidSdkPath=C\:\\Users\\Kurokobi\\AppData\\Local\\Android\\sdk
# unity.androidNdkPath=C\:\\Program Files\\Unity\\Hub\\Editor\\6000.4.4f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK
android.builtInKotlin=false
android.newDsl=false

org.gradle.java.home=C\:\\Program Files\\Unity\\Hub\\Editor\\6000.4.4f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\OpenJDK
org.gradle.daemon=false
android.overridePathCheck=true
